// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DocumentGeneration.Client
{
    using Microsoft.Rest;
    using Models;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// </summary>
    internal partial interface IInternalClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Requests document generation.
        /// </summary>
        /// <param name='subscriptionId'>
        /// Identifier of Logic subscription.
        /// </param>
        /// <param name='request'>
        /// Document generation parameters.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<DocumentGenerationRequest>> RequestDocumentGenerationWithHttpMessagesAsync(System.Guid subscriptionId, GenerateDocumentRequest request = default(GenerateDocumentRequest), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Gets document generation request.
        /// </summary>
        /// <param name='subscriptionId'>
        /// Identifier of Logic subscription.
        /// </param>
        /// <param name='requestId'>
        /// Identifier of request to return.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<DocumentGenerationRequest>> GetDocumentGenerationWithHttpMessagesAsync(System.Guid subscriptionId, System.Guid requestId, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Gets URI to document generated for provided request.
        /// </summary>
        /// <param name='subscriptionId'>
        /// Identifier of Logic subscription.
        /// </param>
        /// <param name='requestId'>
        /// Identifier of request which document should be retuned.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<DocumentUri>> GetDocumentWithHttpMessagesAsync(System.Guid subscriptionId, System.Guid requestId, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// List all templates.
        /// </summary>
        /// <param name='subscriptionId'>
        /// Identifier of Logic subscription.
        /// </param>
        /// <param name='configurationId'>
        /// Identifier of configuration to use.
        /// </param>
        /// <param name='hierarchyPath'>
        /// The hierarchy of possible template sources not including the master
        /// location.
        /// For example, if you have a customer "A0001" with a department
        /// "B0001" then the hierarchy path would be "A0001\B0001".
        /// If the department has no template source configured then the
        /// customers templates will be used.
        /// </param>
        /// <param name='subject'>
        /// Subject of created document.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<Template>>> GetTemplatesWithHttpMessagesAsync(System.Guid subscriptionId, System.Guid configurationId, string hierarchyPath = default(string), string subject = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

    }
}
