using Newtonsoft.Json;

namespace Kmd.Logic.DocumentGeneration.Client
{
    /// <summary>
    /// Autogenerated internal client to communicate with Logic Document Generation Service.
    /// </summary>
    internal partial class InternalClient
    {
        public JsonSerializerSettings GetSerializationSettings()
        {
            return this.SerializationSettings;
        }
    }
}