// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DocumentGeneration.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AzureBlobOutputStorageModelOutputStorageCreateUpdateRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// AzureBlobOutputStorageModelOutputStorageCreateUpdateRequest class.
        /// </summary>
        public AzureBlobOutputStorageModelOutputStorageCreateUpdateRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// AzureBlobOutputStorageModelOutputStorageCreateUpdateRequest class.
        /// </summary>
        public AzureBlobOutputStorageModelOutputStorageCreateUpdateRequest(AzureBlobOutputStorageModel properties = default(AzureBlobOutputStorageModel))
        {
            Properties = properties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public AzureBlobOutputStorageModel Properties { get; set; }

    }
}
