// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DocumentGeneration.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AzureOutputStorageValidateResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// AzureOutputStorageValidateResponse class.
        /// </summary>
        public AzureOutputStorageValidateResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// AzureOutputStorageValidateResponse class.
        /// </summary>
        public AzureOutputStorageValidateResponse(bool? isConnectionValid = default(bool?))
        {
            IsConnectionValid = isConnectionValid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isConnectionValid")]
        public bool? IsConnectionValid { get; set; }

    }
}
