// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DocumentGeneration.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DocumentGenerationConfigurationSummary
    {
        /// <summary>
        /// Initializes a new instance of the
        /// DocumentGenerationConfigurationSummary class.
        /// </summary>
        public DocumentGenerationConfigurationSummary()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// DocumentGenerationConfigurationSummary class.
        /// </summary>
        public DocumentGenerationConfigurationSummary(System.Guid? id = default(System.Guid?), System.Guid? subscriptionId = default(System.Guid?), string name = default(string), bool? hasLicense = default(bool?), IList<string> levelNames = default(IList<string>), DocumentGenerationConfigurationEntrySummary templateStorageDirectory = default(DocumentGenerationConfigurationEntrySummary))
        {
            Id = id;
            SubscriptionId = subscriptionId;
            Name = name;
            HasLicense = hasLicense;
            LevelNames = levelNames;
            TemplateStorageDirectory = templateStorageDirectory;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionId")]
        public System.Guid? SubscriptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hasLicense")]
        public bool? HasLicense { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "levelNames")]
        public IList<string> LevelNames { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "templateStorageDirectory")]
        public DocumentGenerationConfigurationEntrySummary TemplateStorageDirectory { get; set; }

    }
}
