// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DocumentGeneration.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DocumentUri
    {
        /// <summary>
        /// Initializes a new instance of the DocumentUri class.
        /// </summary>
        public DocumentUri()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DocumentUri class.
        /// </summary>
        public DocumentUri(string uri = default(string), System.DateTime? uriExpiryTime = default(System.DateTime?))
        {
            Uri = uri;
            UriExpiryTime = uriExpiryTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uri")]
        public string Uri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uriExpiryTime")]
        public System.DateTime? UriExpiryTime { get; set; }

    }
}
