// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DocumentGeneration.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DocumentGenerationRequest
    {
        /// <summary>
        /// Initializes a new instance of the DocumentGenerationRequest class.
        /// </summary>
        public DocumentGenerationRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DocumentGenerationRequest class.
        /// </summary>
        /// <param name="documentFormat">Possible values include: 'Txt', 'Rtf',
        /// 'Doc', 'Docx', 'Pdf'</param>
        /// <param name="state">Possible values include: 'Requested',
        /// 'Completed', 'Failed'</param>
        public DocumentGenerationRequest(System.Guid? id = default(System.Guid?), System.Guid? subscriptionId = default(System.Guid?), System.Guid? configurationId = default(System.Guid?), string templateId = default(string), string language = default(string), string documentFormat = default(string), string hierarchyPath = default(string), string state = default(string))
        {
            Id = id;
            SubscriptionId = subscriptionId;
            ConfigurationId = configurationId;
            TemplateId = templateId;
            Language = language;
            DocumentFormat = documentFormat;
            HierarchyPath = hierarchyPath;
            State = state;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionId")]
        public System.Guid? SubscriptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "configurationId")]
        public System.Guid? ConfigurationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "templateId")]
        public string TemplateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "language")]
        public string Language { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Txt', 'Rtf', 'Doc', 'Docx',
        /// 'Pdf'
        /// </summary>
        [JsonProperty(PropertyName = "documentFormat")]
        public string DocumentFormat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hierarchyPath")]
        public string HierarchyPath { get; set; }

        /// <summary>
        /// Gets possible values include: 'Requested', 'Completed', 'Failed'
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; private set; }

    }
}
