// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DocumentGeneration.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GenerateDocumentRequest
    {
        /// <summary>
        /// Initializes a new instance of the GenerateDocumentRequest class.
        /// </summary>
        public GenerateDocumentRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GenerateDocumentRequest class.
        /// </summary>
        /// <param name="configurationId">Identifier of configuration to be
        /// used.</param>
        /// <param name="key">Key specifying which entry from configuration to
        /// be used.</param>
        /// <param name="templateId">Identifier of template to be used.</param>
        /// <param name="language">Language code in ISO 639-2 format (eg.
        /// en).</param>
        /// <param name="mergeData">Data to be merge into document.</param>
        public GenerateDocumentRequest(System.Guid? configurationId = default(System.Guid?), System.Guid? key = default(System.Guid?), string templateId = default(string), string language = default(string), object mergeData = default(object))
        {
            ConfigurationId = configurationId;
            Key = key;
            TemplateId = templateId;
            Language = language;
            MergeData = mergeData;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets identifier of configuration to be used.
        /// </summary>
        [JsonProperty(PropertyName = "configurationId")]
        public System.Guid? ConfigurationId { get; set; }

        /// <summary>
        /// Gets or sets key specifying which entry from configuration to be
        /// used.
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public System.Guid? Key { get; set; }

        /// <summary>
        /// Gets or sets identifier of template to be used.
        /// </summary>
        [JsonProperty(PropertyName = "templateId")]
        public string TemplateId { get; set; }

        /// <summary>
        /// Gets or sets language code in ISO 639-2 format (eg. en).
        /// </summary>
        [JsonProperty(PropertyName = "language")]
        public string Language { get; set; }

        /// <summary>
        /// Gets or sets data to be merge into document.
        /// </summary>
        [JsonProperty(PropertyName = "mergeData")]
        public object MergeData { get; set; }

    }
}
