// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DocumentGeneration.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SharePointOnlineTemplateModelUpdateEntryRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// SharePointOnlineTemplateModelUpdateEntryRequest class.
        /// </summary>
        public SharePointOnlineTemplateModelUpdateEntryRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// SharePointOnlineTemplateModelUpdateEntryRequest class.
        /// </summary>
        public SharePointOnlineTemplateModelUpdateEntryRequest(string hierarchyPath = default(string), string key = default(string), string name = default(string), SharePointOnlineTemplateModel properties = default(SharePointOnlineTemplateModel))
        {
            HierarchyPath = hierarchyPath;
            Key = key;
            Name = name;
            Properties = properties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hierarchyPath")]
        public string HierarchyPath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public SharePointOnlineTemplateModel Properties { get; set; }

    }
}
