// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DocumentGeneration.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SharePointOnlineTemplateModel
    {
        /// <summary>
        /// Initializes a new instance of the SharePointOnlineTemplateModel
        /// class.
        /// </summary>
        public SharePointOnlineTemplateModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SharePointOnlineTemplateModel
        /// class.
        /// </summary>
        public SharePointOnlineTemplateModel(string clientId = default(string), string tenantId = default(string), string secretKeyOrClientSecret = default(string), string groupName = default(string))
        {
            ClientId = clientId;
            TenantId = tenantId;
            SecretKeyOrClientSecret = secretKeyOrClientSecret;
            GroupName = groupName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public string TenantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "secretKeyOrClientSecret")]
        public string SecretKeyOrClientSecret { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "groupName")]
        public string GroupName { get; set; }

    }
}
