// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DocumentGeneration.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SharePointOnlineTemplateStorageConfigurationDocumentGenerationConfigurationEntryDetails
    {
        /// <summary>
        /// Initializes a new instance of the
        /// SharePointOnlineTemplateStorageConfigurationDocumentGenerationConfigurationEntryDetails
        /// class.
        /// </summary>
        public SharePointOnlineTemplateStorageConfigurationDocumentGenerationConfigurationEntryDetails()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// SharePointOnlineTemplateStorageConfigurationDocumentGenerationConfigurationEntryDetails
        /// class.
        /// </summary>
        public SharePointOnlineTemplateStorageConfigurationDocumentGenerationConfigurationEntryDetails(System.Guid? id = default(System.Guid?), string key = default(string), string name = default(string), SharePointOnlineTemplateStorageConfiguration templateStorageConfiguration = default(SharePointOnlineTemplateStorageConfiguration))
        {
            Id = id;
            Key = key;
            Name = name;
            TemplateStorageConfiguration = templateStorageConfiguration;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "templateStorageConfiguration")]
        public SharePointOnlineTemplateStorageConfiguration TemplateStorageConfiguration { get; set; }

    }
}
