// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DocumentGeneration.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SharePointOnlineTemplateStorageConfiguration
    {
        /// <summary>
        /// Initializes a new instance of the
        /// SharePointOnlineTemplateStorageConfiguration class.
        /// </summary>
        public SharePointOnlineTemplateStorageConfiguration()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// SharePointOnlineTemplateStorageConfiguration class.
        /// </summary>
        /// <param name="templateStorageType">Possible values include: 'Logic',
        /// 'SharePointOnline', 'AzureBlobStorage'</param>
        public SharePointOnlineTemplateStorageConfiguration(string templateStorageType = default(string), string clientId = default(string), string tenantId = default(string), string secretKeyForClientSecret = default(string), string groupName = default(string))
        {
            TemplateStorageType = templateStorageType;
            ClientId = clientId;
            TenantId = tenantId;
            SecretKeyForClientSecret = secretKeyForClientSecret;
            GroupName = groupName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'Logic', 'SharePointOnline',
        /// 'AzureBlobStorage'
        /// </summary>
        [JsonProperty(PropertyName = "templateStorageType")]
        public string TemplateStorageType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public string TenantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "secretKeyForClientSecret")]
        public string SecretKeyForClientSecret { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "groupName")]
        public string GroupName { get; set; }

    }
}
