// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DocumentGeneration.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Template
    {
        /// <summary>
        /// Initializes a new instance of the Template class.
        /// </summary>
        public Template()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Template class.
        /// </summary>
        public Template(string templateId = default(string), IList<string> languages = default(IList<string>))
        {
            TemplateId = templateId;
            Languages = languages;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "templateId")]
        public string TemplateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "languages")]
        public IList<string> Languages { get; set; }

    }
}
